# Generated by Django 5.1.4 on 2024-12-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advicesafariapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('phonenumber', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='resort',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Resort',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
